### PR TITLE
Missing `Result.` module prefix in promise.re

### PR DESCRIPTION
**Pull request by mseri**
Fixes build on ocaml 4.02 (see https://github.com/ocaml/opam-repository/pull/17432)

### CODE REVIEW

**Comment by aantron** [comment]
Thanks! I will take a look at this soon, and also add a 4.02.3 build to Travis to prevent this sort of oversight on my part in the future.

**Comment by aantron** [comment]
Oops, I hadn't seen that this was a PR, not an issue, from the UI I was using! Sorry about that.

**Comment by aantron** [comment]
Fixed the author :)

**Comment by mseri** [comment]
Ahahah, no worries :D

**Pull request closed without merging**
