### PR TITLE
Run refmt

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
I ran refmt because the code style wasn't unify and it was a bit hard to read.

**Comment by aantron** [comment]
I can't accept a global PR like this without more details. This changes the entire project for reasons that are not clearly stated.

- Which part(s) did you find difficult to read? I would be happy to take a look at those specific parts.
- What specifically about the code style is not unified? I scrolled through the first couple files in the diff and recognized the existing code style as unified at least there. In fact, I deliberately avoided refmt because IMO its output is much less unified. I would be happy to hear *specific* arguments about where I am wrong and refmt (or any other style) is right. Some things I did are arguably "experimental," I'm not pretending that the style of this project right now is perfect.

**Comment by imbsky** [comment]
refmt is neither good nor bad, but many projects have adopted refmt, and if adopt refmt style, it can stop many code style discussions and developers need only get used to the refmt style.

**Comment by imbsky** [comment]
We can also use refmt to add the necessary semicolons, or remove the unnecessary ones.

**Pull request closed without merging**
